services:
  whatsfinance:
    build: .
    container_name: whatsfinance-bot
    restart: always
    volumes:
      - ./data:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "3"
